apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- cm.yaml
- secrets.yaml
- job_migration.yaml
- deploy_service.yaml
- stateful_courier.yaml
- service.yaml

configMapGenerator:
- name: identity-configmap
  behavior: merge
  files:
    - identity.schema.json=cfg/identity.schema.json
    - oidc_google.jsonet=cfg/oidc_google.jsonet
    - oidc_line.jsonet=cfg/oidc_line.jsonet
    - oidc_apple.jsonet=cfg/oidc_apple.jsonet