services:
  kratos-migrate:
    image: oryd/kratos:latest
    environment:
      - postgres://cloud_test:1234@oosa-rdb:5432/identities?sslmode=disable&max_conns=20&max_idle_conns=4
    command: -c /home/ory/kratos.yml migrate sql -e --yes
    volumes:
      - ./contrib/oosa-dev:/home/ory
    restart: on-failure
    networks:
    - ${NETWORK_NAME}
  kratos:
    # image: oryd/kratos:v1.1.0-distroless
    image: oryd/kratos:latest
    depends_on:
      - kratos-migrate
    volumes:
      - ./contrib/oosa-dev:/home/ory
    command: serve -c /home/ory/kratos.yml --watch-courier --dev
    # labels:
    #   - traefik.http.services.admin.loadbalancer.server.port=4434
    #   - traefik.http.services.public.loadbalancer.server.port=4433
    #   - traefik.http.routers.public.rule=(Host(`dev-sso.docker.localhost`) || Host(`dev-sso.oosa.life`)) && PathPrefix(`/api`)
    #   - traefik.http.routers.public.service=public
    #   - traefik.http.routers.public.middlewares=api
    networks:
    - ${NETWORK_NAME}