services:
  partivo-identity-migrate:
    image: sjc.vultrcr.com/oosa/identity:1.1.0
    command: -c /secret/identity.json migrate sql -e --yes
    container_name: partivo-identity-migrate
    volumes:
      - ./conf:/config:ro
      - ${SECRET_PATH}/identity.json:/secret/identity.json:ro
    restart: on-failure
  partivo-identity:
    image: sjc.vultrcr.com/oosa/identity:1.1.0
    depends_on:
      - partivo-identity-migrate
    container_name: partivo-identity
    volumes:
      - ./conf:/config:ro
      - ${SECRET_PATH}/identity.json:/secret/identity.json:ro
    command: serve -c /secret/identity.json --watch-courier
    labels:
      - traefik.enable=true
      - traefik.http.services.partivo-sso-admin.loadbalancer.server.port=4434
      - traefik.http.routers.partivo-sso-admin.rule= Host(`sso-admin-dev.arwork.tw`) && PathPrefix(`/api`)
      - traefik.http.routers.partivo-sso-admin.entrypoints=web
      - traefik.http.routers.partivo-sso-admin.service=admin
      - traefik.http.routers.partivo-sso-admin.middlewares=stripprefix-api@file
    healthcheck:
      test: ["CMD", "kratos", "remote",  "status", "-e",  "http://localhost:4434"]
      interval: 1s
      timeout: 1s
      retries: 10
      start_period: 1s
networks:
  default:
    name: oosa-network
    external: true