services:
  identity-migrate:
    image: sjc.vultrcr.com/oosa/identity:v1.0.1
    command: -c /secret/identity.json migrate sql -e --yes
    container_name: identity-migrate
    volumes:
      - ./conf:/config:ro
      - ${SECRET_PATH}/identity.json:/secret/identity.json:ro
    restart: on-failure
  identity:
    image: sjc.vultrcr.com/oosa/identity:v1.0.1
    depends_on:
      - identity-migrate
    container_name: identity
    volumes:
      - ./conf:/config:ro
      - ${SECRET_PATH}/identity.json:/secret/identity.json:ro
    command: serve -c /secret/identity.json --watch-courier
    labels:
      - traefik.enable=true
      - traefik.http.services.admin.loadbalancer.server.port=4434
      - traefik.http.services.public.loadbalancer.server.port=4433
      # - traefik.http.routers.public.rule= Host(`sso-dev.oosa.life`) && PathPrefix(`/api`)
      # - traefik.http.routers.public.entrypoints=web
      # - traefik.http.routers.public.service=public
      # - traefik.http.routers.public.middlewares=stripprefix-api@file
      - traefik.http.routers.admin.rule= Host(`sso-admin-dev.oosa.life`) && PathPrefix(`/api`)
      - traefik.http.routers.admin.entrypoints=web
      - traefik.http.routers.admin.service=admin
      - traefik.http.routers.admin.middlewares=stripprefix-api@file
    healthcheck:
      test: ["CMD", "kratos", "remote",  "status", "-e",  "http://localhost:4434"]
      interval: 1s
      timeout: 1s
      retries: 10
      start_period: 1s
  identity-frontend:
    image: sjc.vultrcr.com/oosa/identity:v1.0.1
    depends_on:
      - identity-migrate
    container_name: identity_frontend
    volumes:
      - ./conf:/config:ro
      - ${SECRET_PATH}/identity_frontend.json:/secret/identity.json:ro
    command: serve -c /secret/identity.json --watch-courier --dev 
    labels:
      - traefik.enable=true
      - traefik.http.services.public-frontend.loadbalancer.server.port=4433
      - traefik.http.routers.public-frontend.rule= Host(`sso-frontend-dev.oosa.life`) && PathPrefix(`/api`)
      - traefik.http.routers.public-frontend.entrypoints=web
      - traefik.http.routers.public-frontend.service=public-frontend
      - traefik.http.routers.public-frontend.middlewares=corsheader@file,stripprefix-api@file

      - traefik.http.services.admin-frontend.loadbalancer.server.port=4434
      - traefik.http.routers.admin-frontend.rule= Host(`sso-frontend-admin-dev.oosa.life`) && PathPrefix(`/api`)
      - traefik.http.routers.admin-frontend.entrypoints=web
      - traefik.http.routers.admin-frontend.service=admin-frontend
      - traefik.http.routers.admin-frontend.middlewares=stripprefix-api@file
    healthcheck:
      test: ["CMD", "kratos", "remote",  "status", "-e",  "http://localhost:4434"]
      interval: 1s
      timeout: 1s
      retries: 10
      start_period: 1s
networks:
  default:
    name: oosa-network
    external: true