
name: Redeploy dev service

on:
  push:
    branches: [ cd ]

jobs:
  portainer:
    runs-on: ubuntu-latest
    steps:
    - name: Update Service via Webhook
      uses: newarifrh/portainer-service-webhook@v1
      with:
        webhook_url: ${{ secrets.DEV_WEBHOOK_URL }}